version: 2

jobs:
  build:
    working_directory: /sourceforts-server
    docker:
      - image: docker
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /sourceforts-server
      - checkout
      - run: |
          docker build -t sourceforts/steamcmd:debian-$CIRCLE_BUILD_NUM -t sourceforts/steamcmd:debian -t sourceforts/steamcmd:latest .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push sourceforts/steamcmd:debian-$CIRCLE_BUILD_NUM
          docker push sourceforts/steamcmd:debian
          docker push sourceforts/steamcmd:latest

workflows:
  version: 2
  main:
    jobs:
      - build:
          context: sourceforts-server
          filters:
            branches:
              only: master
